### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by mrtn78** [Logius-standaarden/Digikoppeling-Architectuur#1]
Voor het Rest profiel stel ik voor geen Encryption op te nemen in het koppelvlak. De overwegingen hiervoor zijn:
1. de verbinding is al encrypted op basis van mTLS
2. de content kan ook op applicatie niveau worden encrypted
3. je wilt encryption zo dicht mogelijk bij de databron en client toepassen en niet in een gateway

**Comment by Phering** [comment]
Op dit moment is encryption (en signing ook niet) geen onderdeel van het [DK Rest API profiel](https://github.com/centrumvoorstandaarden/DigikoppelingRestfulApiProfiel)
